pipeline {
    agent any
    
    stages {
        stage('checkout scm') {
            steps {
                script {
                    checkout([$class: 'GitSCM',
                              branches: [[name: '*/master']],
                              userRemoteConfigs: [[url: 'https://github.com/sharwanNotes/Demo.git']]])
                }
            }
        }
        stage('build') {
            steps {
                bat 'mvn package'
            }
        }
    }
}
